'Alterado: Workflows':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'

'Alterado: Configurações Repositório':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

'Alterado: Componentes':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/**'

'Alterado: Imagens':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/img/**'

'Alterado: Estilos':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/shared/styles/**'

'Alterado: Testes':
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.tests.ts'

'Alterado: Documentação':
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
