"workflows":
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/*'
    
"componentes":
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/*'
  
"imagens":
  - changed-files:
      - any-glob-to-any-file:
          - 'src/img/*'

"estilos":
  - changed-files:
      - any-glob-to-any-file:
          - 'src/shared/styles/*'

"testes": 
    - changed-files:
      - any-glob-to-any-file:
        - "**/*.tests.ts"  

  