"Alterado: Workflows":
  - any-glob-to-any-file:
      - '.github/workflows/*'
  
"Alterado: Configurações Repositório":
  - any-glob-to-any-file:
      - '.github/*'

"Alterado: Componentes":
  - any-glob-to-any-file:
      - 'src/components/*'
  
"Alterado: Imagens":
  - any-glob-to-any-file:
      - 'src/img/*'

"Alterado: Estilos":
  - any-glob-to-any-file:
      - 'src/shared/styles/*'

"Alterado: Testes": 
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.tests.ts'
  
"Alterado: Documentação": 
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
