name: Feature Request
description: Sugira algo para adicionar ao Matplotlib!
title: "[ENH]: "
labels: [Nova funcionalidade]
body:
  - type: markdown
    attributes:
      value: |
        Please search the [issues](https://github.com/matplotlib/matplotlib/issues) for relevant feature requests before creating a new feature request.

        **Problema:**

        *Eu sempre fico frustrado quando [...] porque [...]*

        *Eu gostaria se [...] acontecesse quando eu [...] porque [...]*

        *Aqui está uma imagem de exemplo do que estou pedindo [...]*

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Descreva uma maneira de alcançar os objetivos desta solicitação de recurso.
