name: Nova Melhoria ✨
description: Nova Tarefa de Documentação
title: "[Docs]: Descreva o título da tarefa aqui"
labels: ["Documentação"]

body:
- type: textarea
  attributes:
    label: Descrição tarefa
    value: |
        - 
        - **Objetivo:**
        - Descreva o objeto da tarefa aqui.
        - **Etapas:**
        - 1. [ ] Etapa 1 da tarefa
        - 2. [ ] Etapa 2 da tarefa
        - **Responsável:** @NomeDoResponsavel
        - **Revisor:** @NomeDoRevisor
  validations:
    required: true

