name: Nova Tarefa de Documentação
description: Crie uma nova tarefa de documentação do projeto
title: "[Docs]: "
labels: [Documentação]
body:
  - type: input
    id: objetivo
    attributes:
      label: Objetivo
      description: Descreva sobre a nova documentação aqui
      placeholder: Descreva o objetivo aqui
  - type: markdown
    attributes:
      value: |
        **Etapas:**
        1. [ ] Descreva a etapa 1 da tarefa aqui
        2. [ ] Descreva a etapa 2 da tarefa aqui

        **Responsável:** @ResponsavelPorDesenvolver
        **Revisor:** @ResponsavelPorRevisar
        **Prazo de conclusão:** 00-00-0000
