body:
  - type: input
    id: objetivo
    attributes:
      label: Objetivo
      description: Descreva o objetivo da tarefa de documentação
      placeholder: Descreva o objetivo aqui
      required: true
  - type: markdown
    attributes:
      value: |
        **Etapas:**
        1. [ ] Descreva a etapa 1 da tarefa aqui
        2. [ ] Descreva a etapa 2 da tarefa aqui

        **Responsável:** @ResponsavelPorDesenvolver
        **Revisor:** @ResponsavelPorRevisar
        **Prazo de conclusão:** 00-00-0000
